platform:ios,'8.0'
target ‘XianJinDaiSystem’ do
pod 'MJRefresh'
pod 'AFNetworking'
pod 'MBProgressHUD'
pod 'YYModel'
pod 'IQKeyboardManager'
pod 'Masonry'
pod 'HYBNetworking'
pod 'SDWebImage'
pod 'UMengUShare/UI'
pod 'UMengUShare/Social/Sina'
pod 'UMengUShare/Social/WeChat'
pod 'UMengUShare/Social/QQ'
pod 'UMengAnalytics-NO-IDFA'
pod 'FLAnimatedImage'
pod 'MJExtension'
pod 'JPush'
end
